### ISSUE TITLE
Add record credit -> 501 error

### ISSUE THREAD

**Issue by antonym8** [antonym8/Yahweh#20]
![Screenshot (269)](https://github.com/antonym8/Yahweh/assets/142376069/7a210aca-fb1d-42f0-a800-224220615e09)

**Comment by SoundharSm8** [comment]
Fixed @antonym8

**Comment by antonym8** [comment]
Not fixed

![Screenshot (389)](https://github.com/antonym8/Yahweh/assets/142376069/1e6b9c5a-2f71-4722-b89f-03fa915d0db5)
