### ISSUE TITLE
Record expense not created

### ISSUE THREAD

**Issue by antonym8** [antonym8/Yahweh#22]
![Screenshot (271)](https://github.com/antonym8/Yahweh/assets/142376069/15884705-5a32-428d-bbc1-cb9cbd30ad44)

**Comment by SoundharSm8** [comment]
Fixed @antonym8

**Comment by antonym8** [comment]
Not fixed

![Screenshot (391)](https://github.com/antonym8/Yahweh/assets/142376069/d8ffce83-a5f1-4c00-a19f-7ddc719affbe)
