### ISSUE TITLE
Login -> Profile picture removed when update profile without add profile picture

### ISSUE THREAD

**Issue by antonym8** [antonym8/Yahweh#29]
![Screenshot (278)](https://github.com/antonym8/Yahweh/assets/142376069/81d2b33c-9ebd-4ff3-9a52-2d949f40d974)

**Comment by SoundharSm8** [comment]
Fixed @antonym8

**Comment by antonym8** [comment]
Not fixed

[screen-capture.webm](https://github.com/antonym8/Yahweh/assets/142376069/8210fa55-6e81-4288-b569-d6fdfa0957bc)
