### ISSUE TITLE
Add vendor validations

### ISSUE THREAD

**Issue by antonym8** [antonym8/Yahweh#9]
1. Name field accepts numbers
2. Mobile number field accepts string value

![Screenshot (258)](https://github.com/antonym8/Yahweh/assets/142376069/34ff9119-9d5f-41c4-aa72-e41969af311f)

**Comment by SoundharSm8** [comment]
Fixed @antonym8

**Comment by antonym8** [comment]
Not fixed

![Screenshot (388)](https://github.com/antonym8/Yahweh/assets/142376069/92a3b7b4-1b3b-4916-a492-bb09c3b67c8d)
